- command: ln -sf /usr/share/zoneinfo/Europe/Madrid localtime chdir=/etc/
#- file: src=/usr/share/zoneinfo/Europe/Madrid dest=/etc/localtime state=link
  when: "cloud == 'ec2'"

- include: blcr.yml
  when: "cloud == 'one'"

- include: blcr-ec2.yml
  when: "cloud == 'ec2'"

- include: slurm_front_2_5.yml
  when: "slurm_type_of_node == 'front'"
  
- include: slurm_wn_2_5.yml
  when: "slurm_type_of_node == 'wn'"
  
- include: pyslurm.yml
  when: "slurm_type_of_node == 'front'"
  
- include: nfs_front.yml
  when: "slurm_type_of_node == 'front'"

- include: nfs_wn.yml
  when: "slurm_type_of_node == 'wn'"

- include: ckptman.yml
  when: "slurm_type_of_node == 'front'"
